options:
  debug:
    type: boolean
    default: true
    description: |
        *DEPRECATED* Enable debug logging
  snapshot:
    type: boolean
    default: true
    description: |
        *DEPRECATED* Enable log snapshots
